### PR TITLE
Feature/576

### PR DESCRIPTION
**Pull request by ggAlexS**
Needed for https://github.com/aau-giraf/weekplanner/issues/576

### CODE REVIEW

**Comment by Determinatoro** [comment]
Please use the following checklist, @twaxlol. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] Error messages in the code are understandable

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need be covered by tests
- [ ] The functionality needs to be covered by tests

Only use if the functionality needs to be covered by tests:
- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Comment by Determinatoro** [comment]
Please use the following checklist, @ZohraAmini. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] Error messages in the code are understandable

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need be covered by tests
- [ ] The functionality needs to be covered by tests

Only use if the functionality needs to be covered by tests:
- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Review by twaxlol — APPROVED** [review]

**Comment by ZohraAmini** [comment]
I can't run feature 576 on emulator. When trying to change the pubspec.yaml (url: https://github.com/aau-giraf/api_client.git
      ref: feature/576)
To get the right wep-api files, rxdart has to be deleted from pubspec.yaml

**Review by ZohraAmini — CHANGES_REQUESTED** [review]
See comment for the weekplanner feature 576, the pull request 620
Merge develop branch into the feature branch, problems occur due to rxdart

**Review by ZohraAmini — APPROVED** [review]

**Pull request merged**
