### PR TITLE
Feature/673

### PR DESCRIPTION
**Pull request by mikejensen0**
# Description

Expanded settings model to support showPopup setting.

Fixes part of #673

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This has only been unit tested using *flutter test --coverage*

**Development Configuration**
*Type "flutter --version" and "dart --version" in your CMD to check versions.*

* Flutter version: 2.0.5
* Dart version: 2.12.3

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, if necessary
- [x] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works, if necessary
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

### CODE REVIEW

**Review by JJTM20 — APPROVED** [review]
lgtm

**Review by Lildhansen — APPROVED** [review]
ser sgu fint ud

**Review by Lildhansen — APPROVED** [review]
den ser stadig fin ud

**Comment by makelblack159** [comment]
dette virker ikke da den ikke kan sende det til databasen

**Pull request merged**
